services:
  app:
    image: php:8.2-apache
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./config/laravel.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - "8080:80"
    networks:
      - laravel

networks:
  laravel: